- name: frontend application
  hosts: frontend
  become: yes
  tasks:
  - name: Disabling the nginx 
    ansible.builtin.dnf:
      name: nginx
      state: absent
  
  - name: Enabling the nginx
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: installing the nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: enabling and starting the nginx
    ansible.builtin.service:  
      name: nginx
      state: started
      enabled: yes

  - name: removing the delete directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  
  - name: creating the html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Download frontend code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unzip frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html 
      remote_src: yes

  - name: remove default nginx conf 
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent 

  - name: copy roboshop nginx conf
    ansible.builtin.copy:
      src: nginx.conf 
      dest: /etc/nginx/nginx.conf

  - name: restart the nginx
    ansible.builtin.service:
      name: nginx
      state: restarted