- name: Configure {{ component }} 
  hosts: "{{ component }}"
  become: yes
  roles: # this will automatically load a folder called roles in the current directory
  - "{{ component }}"

  #ansible-playbook -i inventory.ini -e "component=mongodb" main.yaml