- name: "configure {{ component }}"
  become: yes
  hosts: "{{ component }}"
  vars_files:
  - vault/mysql.yaml
  roles: # this will automatically load a folder called roles in current working directory.
  - "{{ component }}"

  #ansible-playbook -i inventory.ini -e "component=mongodb" main.yaml