- name: Payment component
  hosts: payment
  become: yes
  tasks:
  - name: installing the python 
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: installed
    loop:
    - python3 
    - gcc 
    - python3-devel

  - name: creating the /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: creating the non-system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app
  
  - name: Download catalogue code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip

  - name: Extract the catalogue code
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes  # already exists in remote server

  - name: installing python dependencies
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app

  - name: copy the payment.repo file
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service
  
  - name: Daemon-reload
    ansible.builtin.systemd_service:
      daemon-reload: true

  - name: Enabling and starting the payment
    ansible.builtin.service:
      name: payment
      state: started
      enabled: yes