- name: RabbitMQ Component
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copying the rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: installing the rabbitmq
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: installed

  - name: enabling and starting the service
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: create rabbitmq user
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present