- name: Shipping Component
  hosts: shipping 
  become: yes
  tasks:
  - name: disabling the nodejs
    ansible.builtin.dnf:
      name: maven
      state: present

  - name: Install pythonMYSQL package
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL

  - name: creating the /app directory
    ansible.builtin.file:
      path: /app 
      state: directory

  - name: creating the non-system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: Download the Shipping zip file 
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: Extract the Shipping file
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: install the maven dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename jar files
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copy the shipping service file
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: Daemon reload for shipping Component
    ansible.builtin.systemd_service:
      daemon-reload: true

  - name: Enabling and starting the shipping Component
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes

  - name: Installing mysql client
    ansible.builtin.dnf:
      name: mysql
      state: installed
  
  - name: Loading the data 
    tags:
    - import
    community.mysql.mysql_db:
      name: all
      state: import
      login_user: root 
      login_password: RoboShop@1
      login_host: mysql.pavithra.fun
      target: "{{ item }}"
    loop: 
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

  - name: restarting the shipping Component
    ansible.builtin.service:
      name: shipping
      state: restarted