- name: Stop the catalogue
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{ component }}"
    state: stopped

- name: Remove /app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create the /app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download application
  tags:
  - deployment
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v{{ app_version }}.zip
    dest: /app
    remote_src: yes

- name: install dependencies
  tags:
  - deployment
  community.general.npm:
    path: /app

- name: restart {{ component }}
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted