- name: installing the maven and mysql
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - maven
  - mysql

- name: Install pythonMYSQL package
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - cryptography
  - PyMySQL

- name: install the maven dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: rename jar files
  ansible.builtin.command: mv target/{{ component }}-1.0.jar {{ component }}.jar
  args:
    chdir: /app