- name: installing the python 
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: installed
  loop:
  - python3 
  - gcc 
  - python3-devel

- name: installing python dependencies
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3.9
  args:
    chdir: /app