- name: copy catalogue service to systemd directory
  ansible.builtin.template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: systemctl Daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true
  
- name: Enabling and starting the catalogue
  ansible.builtin.service:
    name: catalogue
    state: started
    enabled: yes